"""add analytics columns

Revision ID: e1fef47ecf42
Revises: 896463f0393c
Create Date: 2026-09-10 18:59:22.699274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fef47ecf42'
down_revision: Union[str, Sequence[str], None] = '896463f0393c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_pick_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_chosen_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('last_chosen_at')
        batch_op.drop_column('manual_pick_count')

    # ### end Alembic commands ###
